#!/usr/bin/env bash
# install nginx on the server
apt-get install nginx -y
ufw allow 'Nginx HTTP'
service nginx start
echo 'Hello World!' > /var/www/html/index.nginx-debian.html
service nginx restart
