#!/usr/bin/env bash
# install nginx on the server
apt-get install nginx -y
ufw allow 'Nginx HTTP'
echo 'Hello World!' >> /var/www/html/index.html
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www
sed -i '371\rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
service nginx start
