#!/usr/bin/env bash
# install nginx on the server
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo "Hello World!" >> /var/www/html/index.html
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www
sed -i '37i\rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
echo "Ceci n'est pas une page\n" >> /var/www/html/error_404.html
sed -i '38i\error_page 404 /error_404.html;' /etc/nginx/sites-available/default
service nginx star
