#!/usr/bin/env bash
# script that configures a server and add a custom header
# shellcheck disable=SC2154
sed -i "/listen 80 default_server;/a add_header X-Served-By $hostname;" /etc/nginx/sites-available/default
