#!/usr/bin/env bash
# script that installs an haproxy loadbalancer and directs traffic to my servers
sudo apt update
sudo apt-get install -y haproxy
sudo echo "ENABLED=1" | sudo tee -a "/etc/default/haproxy"
echo "
frontend load_balancer
    bind *:80
    default_backend servers
    option forwardfor

backend servers
    balance roundrobin
    server 323922-web-01 54.175.253.42:80 check
    server 323922-web-02 54.237.103.128:80 check
" >> /etc/haproxy/haproxy.cfg
service haproxy start
