#!/usr/bin/env bash
# This script pings the IP address given as argument
address=$1
if [[ "$address" != "" ]]
then
	ping -c 5 "$address"
else
	echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
fi
