#!/usr/bin/env bash
# This script displays numbers from 1 to 100 
# if the number is a multiple of 3 and 5 display "FizzBuzz" 
# "Fizz" when the number is a multiple of 3 only
# "Buzz" when the number is a multiple of 5 only
for i in {1..100}
do
    if [ $((i % 3)) -eq 0 ] && [ $((i % 5)) -eq 0 ];
    then
        echo "FizzBuzz"
    elif [ $((i % 3)) -eq 0 ]
    then
        echo "Fizz"
    elif [ $((i % 5)) -eq 0 ]
    then
        echo "Buzz"
    else
        echo $i
    fi
done