#!/usr/bin/env bash
# Loop from 1 to 20 with "bad luck from China" after 4, "bad luck 
# from Japan" after 9 and "bad luck from Italy" after 19
# and "Best School" in others
i=1
while [ $i -le 20 ];
do
    case $i in 
        "4")
        echo $i
        echo "bad luck from China"
        ;;
        "9")
        echo $i
        echo "bad luck frmo Japan"
        ;;
        "17")
        echo $i
        echo "bad luck from Italy"
        ;;
        *)
        echo $i
        ;;
    esac
    ((i++))
done