#!/usr/bin/env bash
# This script displays time for 12 hours and 59 mins
i=0
while [ $i -le 12 ];
do
    echo "Hour: $i"
    j=1
    while [ $j -le 59 ]
    do
        echo "$j"
        ((j++))
    done
    ((i++))
done