#!/usr/bin/env bash
# script that makes nginx run using nginx user privilleges for security
sudo chown nginx:nginx /etc/nginx/nginx.conf
sudo chmod u+rw /etc/nginx/nginx.conf
sudo -u nginx service nginx start
