#!/usr/bin/env bash
# script that makes the solution for the first task more sweet
chown nginx:nginx /etc/nginx/nginx.conf
chmod o+rwx /etc/nginx/nginx.conf
sed -i 's/80/8080/g' /etc/nginx/sites-available/default
sudo -u nginx service nginx start
