#!/usr/bin/env bash
# script that makes the solution for the first task more sweet
chown nginx:nginx /etc/nginx/nginx.conf
chmod 777 /etc/nginx/nginx.conf
pkill apache2
sed -i 's/80/8080/g' /etc/nginx/sites-available/default
sudo -u nginx service nginx start
